Controllers/AdminController.cs
using BooksStore.Data;
using BooksStore.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Models;
using NuGet.Protocol.Core.Types;
using System.Net;
using static System.Reflection.Metadata.BlobBuilder;

namespace BooksStore.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private readonly ApplicationDbContext _db;
        public AdminController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            var BooksList = _db.Books.ToList();
            return View(BooksList);
        }

        public IActionResult Edit(int bookId)
        {
            Book? book = _db.Books.FirstOrDefault(g => g.Id == bookId);
            return View(book);
        }
        [HttpPost]
        public IActionResult Edit(Book book)
        {
            if (ModelState.IsValid)
            {
                if (book.Id == null)
                    _db.Books.Add(book);
                else
                {
                    Book? dbEntry = _db.Books.Find(book.Id);
                    if (dbEntry != null)
                    {
                        dbEntry.Name = book.Name;
                        dbEntry.Price = book.Price;
                        dbEntry.Category = book.Category;
                    }
                }
                _db.SaveChanges();
                TempData["message"] = string.Format($"Changes for {book.Name} have been saved!");
                return RedirectToAction("Index");
            }
            else
            {
                return View(book);
            }
            
        }
        public IActionResult Create()
        {
            return View("Edit", new Book());
        }
        public IActionResult DeleteBook(int Id)
        {
            Book? book = _db.Books.Where(o => o.Id == Id).FirstOrDefault();
            if (book!=null)
            {
                _db.Books.Remove(book);
            }
            _db.SaveChanges();

            TempData["message"] = string.Format("The book has been removed!");
            return RedirectToAction("Index");
        }
        public IActionResult ListOfOrders()
        {
            var listOfOrders = _db.Orders.ToList();
            return View(listOfOrders);
        }

        public IActionResult DeleteOrder(int OrderID)
        {
            Order? order = _db.Orders.Where(o => o.OrderID == OrderID).FirstOrDefault();
            if (order!=null)
            {
                _db.Orders.Remove(order);
            }
            _db.SaveChanges();

            TempData["message"] = string.Format("The Order has been removed!");
            return RedirectToAction("ListOfOrders");
        }
        public IActionResult OrderDetails(int OrderID)
        {
            Order? order = _db.Orders.Where(o => o.OrderID == OrderID).FirstOrDefault();
            List<Book>? AllBooks = _db.Books.ToList();
            List<Book>? BooksInOrder= new List<Book>(); ;
            string[] asd = order.booksList.Split(',');
            int[] booksId = new int[asd.Length];
            int counter=0;
            foreach (var sub in asd)
            {
                if (Int32.TryParse(sub, out int numValue))
                {
                    booksId[counter]=numValue;
                    counter++;
                }
                else
                {
                    continue;
                }
            }

            foreach (var item in booksId)
            {
                try
                {
                    Book? book = AllBooks.Where(o => o.Id == item).FirstOrDefault();
                    if (order != null)
                    {
                        BooksInOrder.Add(book);
                    }
                }
                catch (Exception)
                {

                    throw;
                }
                
            }

            return View(BooksInOrder);
        }
    }
}

Controllers/CartController.cs
using BooksStore.Data;
using BooksStore.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace BooksStore.Controllers
{
    public class CartController : Controller
    {
        private readonly ApplicationDbContext _db;
        public static Cart? _cart;
        public CartController(ApplicationDbContext db, Cart cart)
        {
            _db = db;
            _cart = cart;
        }

        public IActionResult Index()
        {
            _cart.ListCartItem = _cart.GetCartItems();

            return View(_cart);
        }

        public ActionResult AddToCart(int Id)
        {
            Book? item = _db.Books.FirstOrDefault(i => i.Id == Id);
            if (item != null)
            {
                _cart.AddToCart(item);
            }
            return RedirectToAction("Index");
        }
        public ActionResult RemoveFromCart(int Id)
        {
            CartItem? item = _db.CartItem.FirstOrDefault(i => i.Id == Id);
            if (item != null)
            {
                _cart.RemoveFromCart(item);
            }

            TempData["message"] = string.Format("The book has been removed!");
            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BooksStore</title>
    <link rel="stylesheet" href="~/css/bootswathTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BooksStore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Administration</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Book List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="ListOfOrders">Orders</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <body>
        <div>
            @if (TempData["message"] != null)
            {
                <div class="alert alert-success">@TempData["message"]</div>
            }
            @RenderBody()
        </div>
    </body>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BooksStore</title>
    <link rel="stylesheet" href="~/css/bootswathTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BooksStore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BooksStore</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Shop</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index">Cart</a>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Administration</a>
                        </li>
                            </li>
                        </ul>
                    </div>
                </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - BooksStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>